CREATE DATABASE HotelDB;

USE HotelDB;


CREATE TABLE Hotel (
    HotelID INT IDENTITY PRIMARY KEY,
    Name VARCHAR(100) NOT NULL UNIQUE,
    Location VARCHAR(100) NOT NULL,
    ContactNumber VARCHAR(15) NOT NULL UNIQUE,
    Rating DECIMAL(2, 1)
);


CREATE TABLE Room (
    RoomID INT IDENTITY PRIMARY KEY,
    HotelID INT NOT NULL,
    RoomNumber INT NOT NULL,
    Type VARCHAR(50) NOT NULL CHECK (Type IN ('Single', 'Double', 'Suite')),
    PricePerNight DECIMAL(10, 2) NOT NULL CHECK (PricePerNight > 0),
    IsAvailable BIT DEFAULT 1, 
    UNIQUE (HotelID, RoomNumber),
    FOREIGN KEY (HotelID) REFERENCES Hotel(HotelID) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE Guest (
    GuestID INT IDENTITY PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Contact VARCHAR(15) NOT NULL,
    IDProofType VARCHAR(50) NOT NULL,
    IDProofNumber VARCHAR(50) NOT NULL
);


CREATE TABLE Booking (
    BookingID INT IDENTITY PRIMARY KEY,
    GuestID INT NOT NULL,
    RoomID INT NOT NULL,
    BookingDate DATE NOT NULL,
    CheckInDate DATE NOT NULL,
    CheckOutDate DATE NOT NULL ,
    Status VARCHAR(50) NOT NULL ,
    TotalCost DECIMAL(10, 2) NOT NULL CHECK (TotalCost > 0),
    FOREIGN KEY (GuestID) REFERENCES Guest(GuestID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (RoomID) REFERENCES Room(RoomID) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE Payment (
    PaymentID INT IDENTITY PRIMARY KEY,
    BookingID INT NOT NULL,
    PaymentDate DATE NOT NULL,
    Amount DECIMAL(10, 2) NOT NULL CHECK (Amount > 0),
    Method VARCHAR(50) NOT NULL,
    FOREIGN KEY (BookingID) REFERENCES Booking(BookingID) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE Staff (
    StaffID INT IDENTITY PRIMARY KEY,
    HotelID INT NOT NULL,
    Name VARCHAR(100) NOT NULL,
    Position VARCHAR(50) NOT NULL,
    ContactNumber VARCHAR(15) NOT NULL,
    FOREIGN KEY (HotelID) REFERENCES Hotel(HotelID) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE Review (
    ReviewID INT IDENTITY PRIMARY KEY,
    HotelID INT NOT NULL,
    GuestID INT NOT NULL,
    ReviewDate DATE NOT NULL,
    Rating INT NOT NULL CHECK (Rating BETWEEN 1 AND 5),
    Comments VARCHAR(255) 
    FOREIGN KEY (HotelID) REFERENCES Hotel(HotelID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (GuestID) REFERENCES Guest(GuestID) ON DELETE CASCADE ON UPDATE CASCADE
);
